1) Recover YAML reading part in decomposition WARNING - For diagonalization, Default.yaml is now required in the same directory that you start program - We are using newer than C++11 thus we need to carefully install YAML-CPP library. if not, you will face the error (Undefined reference to YAML::LoadFile)   please refer more detailed explanation from the following URL   https://github.com/jbeder/yaml-cpp/issues/591#issuecomment-1699740893